spring:
  cache:
    type: redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 3000
    jedis:
      pool:
        max-idle: 200
        min-idle: 8
        max-active: 200
        max-wait: 8000
  #Dubbo 服务消费者配置
  dubbo:
    application:
      name: mng-consumer
    registry:
      address: zookeeper://192.168.1.7:2181
    scan: com.zcs.boot.server
  #数据库配置
  datasource:
    url: jdbc:mysql://192.168.1.8:3306/admin
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    open-in-view: true






